name: If test
on:
  workflow_dispatch:
    inputs:
      Version:
        type: string
        default: latest
        required: true
      name:
        type: choice
        description: 'Environment'
        options: 
        - Development
        - Staging
        - Production
        required: true
      Verification:
        type: string
        required: false
        
jobs:
    development-deploy:
        if: ${{ github.event.inputs.name == 'Development' }}
        runs-on: ubuntu-latest
        steps:
        - run: |
             date
             echo Development
    staging-deploy:
        if: ${{ github.event.inputs.name == 'Staging' }}
        runs-on: ubuntu-latest
        steps:
        - run: |
             date
             echo Staging
    production-deploy:
        if: ${{ github.event.inputs.name == 'Production' }} && ${{ github.event.inputs.Verification == 'production' }}
        runs-on: ubuntu-latest
        steps:
        - run: |
             date
             echo Production
